apiVersion: v1
kind: Service
metadata:
  name: littefashion-service
spec:
  selector:
    app: littefashion-deployment
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31000  # Specify your desired NodePort here
